version: 2
jobs:
  test:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run:
          name: Make report directory
          command: mkdir report
      - run:
          name: Download Selenium Standalone
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium Standalone
          command: java -jar selenium-server-standalone-3.5.3.jar -log report/selenium.log
          background: true
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: ESlint check
          command: npm run eslint-check
      - run:
          name: Run Test
          command: npm test wdio.conf.js
      - store_test_results:
          path: report
workflows:
  version: 2
  test:
    jobs:
      - test
